[versions]
kotlin = "2.4.10"
sqldelight = "2.3.2"
kmpCore = "0.1.0-SNAPSHOT"

[libraries]
advanced-hello-world-kmp-core = { module = "io.github.yutakax17.advancedhelloworld:kmp-advanced-hello-world-core", version.ref = "kmpCore" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
